### ISSUE TITLE
Spellcheck fails with uninformative error

### ISSUE THREAD

**Issue by hadley** [ropensci/spelling#4] opened 2017-10-21 16:00 UTC
```
> spelling::spell_check_package(pkg = ".", vignettes = TRUE, lang = "en_US")
Error in hunspell::dictionary(lang, add_words = sort(ignore)) : 
  unused argument (add_words = sort(ignore))
```

**Comment by jeroen** [comment] 2018-12-14 14:19
I can't reproduce this but I think you were running an outdated version of `hunspell`. This was probably fixed in https://github.com/ropensci/spelling/commit/b2ce8e46ab46b4afe82c8d732303b57f24bb437f when we require at least hunspell 2.9.

**Closed by jeroen** 2018-12-14 14:19 UTC
